language: node_js
node_js: 5
before_install:
  - 'git config --global user.email "algoliaplacesbot@users.noreply.github.com"'
  - 'git config --global user.name "algoliaplacesbot"'
  - npm prune
  - rvm install 2.3.0
  - rvm use 2.3.0
install: npm install
script: ./scripts/test-ci.sh
branches:
  only:
    - master
notifications:
  slack: algolia:wSMHl9gxKQ7cRvnOPUWE9esI
sudo: false
cache:
  - bundler
  - directories:
    - node_modules
