language: ruby
before_install:
- 'PATH=`echo $PATH | sed "s/\.\/node_modules\/\.bin//g"`; export PATH=$PATH:./node_modules/.bin;

'
- git config --global user.email "algoliaplacesbot@users.noreply.github.com"
- git config --global user.name "algoliaplacesbot"
- rvm install 2.4.0
- rvm use 2.4.0
- nvm install stable
- nvm use stable
- npm install --global yarn
gemfile: docs/Gemfile
script:
- yarn
- npm run test:ci
branches:
  only:
  - master
  - "/^greenkeeper-.*$/"
notifications:
  slack: algolia:wSMHl9gxKQ7cRvnOPUWE9esI
sudo: false
cache:
  bundler: true
  directories:
  - node_modules
  - "~/.yarn"
  - "~/.nvm"
env:
  global:
  - secure: FvNhotbMfsYm+q1UNEUX9aWYKDePjwu5uUDkd5gcsN3mvT8BmjJekDc+PvCqwaG53y7XZ1iXAmIYzm8AUPkUzum32NoRL0bLn/mAu/qXItv0nAOU4lvkCrH3uLeC5Sf3IEZh6UiZxzyPMyu0pV7yyLJLhtR1C60KX+BdpdWy8Je8307c8jdesa+VwUAJ822OvW0lfSxfAeOfMEbNaBU2VNFgQQpvzMeA2lWqWjRzVRZ2h1F+TRSKFcI4czGYyVnYBQaRzp5/44KjIU0edQ1lW5vNjqGjXp4xxCB3/GnqyNWukLvLJfoxNtN+zzCLK4mKUjK8EeBX9zWxGTl2YPtNG5CrsX7lBHJQ52/XEc9oV9wcNodn4KlG/bsVwRSwiLIyFewSBY3h+Aqvv/RnANVDeEWrhB1NVIIGyiRQFpDUjoxceI7Mm7jSIYN6R1TOvwG/7FW7CnwGb9I1v4Ra2ixWg4e/xULSEboZZkLvCI+MpCHQwpk11exjhF3etpPv47rFd6PiumeCsJxSPeFp6N2erRHayl0KhGq9toH9pMKdlu/fy2dWz1QLVe57ClEfDvz+mn89z467L2oLkQC3gi4szM1VwFPxR7TPx0dw4/nmNwQpivDVoPzYswtsqNxgH5BsXL9L3DFhRGrLyDvEkmFpFMhhCvLJQDB3KjPaxG5FQaA=
  - secure: xseRN3SzIwT2mMs4u0j7S/EfRS/DfGCyhIPfEfrZisuzEc81ziZep41j6pCi38TgYzFGxgxQRFr1IhS1aPHZW2mT5LWneNkXX5aN3nAfaTQio3i4an6YR7OEn1DYi/GZdxx+322RiUGXk8xowjWBNILd+ffTsrIKGk6rPC+TVT5IwfHfeKO8U5/OZSjTXGAh6GGyFBwmTNKpSk+VUC5PiT0NH8inV6/NF9Q3M56/6ZXUiJ1TloTnGpnyqOTBXj2wIc5X6bcz73eSPEV06+B1OrCw5FKjXNh6HAjdM2nh/c7jTsiewl1dh73I01jb2bfmh4YVQx+qbRZxotHtaeQzLE+tNMbITAf9qGD1BmdrlRSOTgG22J+VfS5tNATo4Dq1wq2soUtYeL+BeE5iIZVEwefXSVJJoM5Err0qeTm57mO3LDh/gVT7hFZ55tY55eV8aAPHhH4dqRKV1dmiklJqWE/qX4lw7n/20U3ZwluyinpU3QypXQLNu7jbmtrA6xEGHkTbgPDSizAE6KiAFbvNYeS3YEeT0ea5hLe+Jg+SpRfLrFoFkyqE27bccGxu3XzBb1DxDG/A5quIAZm1wg2ubfNGS+h0DaJDIaY3Nx/vC8Y11LfhoAJR9jWgYTDOs5Vvho5rnaW9haedQN4lAZ/FjagUD0s7zMmCzuPUnIvclck=
