# This travis.yml was built to:
#   - install ruby and nodejs
#   - run nodejs test
#   - lint javascript code
#   - check commit message style when in a PR
#   - deploy website when merged to master
# We defined the language to be ruby to benefit from bundle caching, it seems to be the only way to have it
# working well in travis.
# Then we install ruby and nodejs with rvm and nvm
# We also cache ./node_modules/
language: ruby
before_install:
  - 'git config --global user.email "algoliaplacesbot@users.noreply.github.com"'
  - 'git config --global user.name "algoliaplacesbot"'
  - npm prune
  - rvm install 2.3.0
  - rvm use 2.3.0
  - nvm install 5
  - nvm use 5
gemfile: docs/Gemfile
script:
  - npm install
  - npm run test:ci
branches:
  only:
    - master
notifications:
  slack: algolia:wSMHl9gxKQ7cRvnOPUWE9esI
sudo: false
cache:
  bundler: true
  directories:
    - node_modules
env:
  global:
    # CACHE_URL
    - secure: XLMdiRlG9dU0EdFGt3eGioEF4YGbhMjn4AsbVJsSYRUXXRgLJRul5N0lhvNf7efwvCbTkQko6c7BbZDHYB+9iPwWxk+EEuFIU8CcU/Yn6J/l0jah/B4xDOz0YwL/EXJEccS3drRTKYkAtyz7h8cofCk6c2IJpXwNbuUviudi/BOEogf5ECe9FCzErK6+mJ0M96z8vZQ49TNT50zxds8Z976acp610M3KkIA1owA0jFCjsyY0gUZEeU20CnCcapP30ONgZOSh8CW5vX4CM0a7MjknuiE3VHTbEu6C48hvraWr+mTyWKYvYj396UdC9EA6YMTA0ZJEVrt45QDm5o3h1fCJmYXNUBptWfw1/fFaXl9QhaeaXg7+9XvqaDYt0pq9QLxPxYXgX8G1O0vM+SwcDXMbbhwjIJtRkHFbsRyc9wRztWv6D9qUwDTiutypB+ptX5Y0J1p4KfML/PUhe5HInGYcjEgSlwCwBQrBGGdNKJyFXNU168JAgd6POMbxXEDdVIVMlsJbfUwZZ0bOfwuBGsib2eOTDD3yepqC0ixmQlDSWkNdAkvsqVz851NssDKeSDoaofrktGQ/dIBKWkeav/Yxq99Gz8XbQtqnh0+yKxirR+BGr0+ZQXnLJ9DSmwGTF4lYFHyitFlUNE5OL/1mFl1wvDPx1aqAfKyjnasWn4A=
    # GH_TOKEN
    - secure: V55rGCcFyxIo3nIByQlxvZIE/hRwCstyvIfqvPXUbcFYwkEe4T6LQBuwXw5MqBMXlB/xwOuWlsG8o7MWYmbMnANG8mLa8/7dLvwqHZdbGOIsTnx5G6GwcPijjnevK91UorgY5y5IU/MvCy6PkkJa7EEzKpocvSe+TjfgDQA1HK7q1GrAIuInVzlv0+q2Z0+BVLJuP2CEr40WlGDEGYQerUQM+ONaRx9XHMLyy05akjevYADb3BD/Unv8xRFaaV5fy9sZfNLZDWUMKpAAzmomuabJSg8eQ+t+dDcZi436t+tvAjb6+B2Ql5fnNPJENkCQqYWlzdHAq/V9ADZhAURowC5zepcfmaLNT/eoEnLFRypoxfpqgxyHSgqdQ7uW6NMLAr8HL/baaMvLrr0vuOMZ3Mvb7XxNsscp/hmeeMAVw2BTSV0CoHnKbC6saMry2Ng+cKQ5qmo9NSHsyriRS51JxB1RA2qtsJrA5lBnLiBMUi5MkYXd3OYr0mUGEvcHYa/Z/Szx/LvOkPCkEvvKpVgTAIm5RGtFuML4bJP379qDd/0ORBwOEA4aFWjKZpePhN5UvjGkdcROGEXB9DtXvM0Q/Oj9zkwYIaJ60kX+0ayufizgk20+m3GzfmSpqSAfyCQjqvcO3s3a+E/561GvbuACtTQr/JIrnToUfXujEbakzIQ=
