language: node_js
node_js: stable
before_install:
- git config --global user.email "algobot@users.noreply.github.com"
- git config --global user.name "algobot"
- rvm install 2.4.0
- rvm use 2.4.0
- "(cd docs && bundle install)"
script:
- npm run test:ci
branches:
  only:
  - master
notifications:
  slack: algolia:wSMHl9gxKQ7cRvnOPUWE9esI
sudo: false
cache:
  bundler: true
  yarn: true
  directories:
  - node_modules
env:
  global:
    secure: o9jGb6EMsAv955rn+Mu1GPLX+3aA6j5POM5rjq3X3T+zRSV5eBEnP8TiRSmUqIz+aLXmvQMKsCJsFc4oI9udjotjwBUXKvl4Zq7Ph45iVunQLi06Bp+4DaB7pSrAn/qeY5R2P38jIonN5nitjDQSf/htgxsvurC8aX0QR1Bp4TdQNVQUuedaGjHfGitBDwgGIjU7LatHwPKguJA/NnKKg9qFZNJDrZ3Wb9O9//RJyWxcnYF4JEVKztgk7I+vGXkN7a7mpCsesUxS6qjs2MRTY7qjFRXHV3HrltLEwYs6z+0ijmTJl3e6W8KO1kKj3qfQCTpkZV1R6YWDtefKpQfzW0SBFgTX8rJ/pnt+o0DxLRFzHpnUCZBcAqvtjZOzwP2qJyqI3S9LGLZ6QZ2OpqTGamBm4DLrAUmeB84jImbgj2buiRDMStY0ut2z9RURdr2zWSUouVojjJmlhbBTWvwGk6x6ZbQy1P+SZGSzjXbKn25X9c14B6OJUjv5NFdDZf4zxWdYaMhX8tum+SMvnwZjoGC57R+WyrN0M27Xu0OAO30PyEFTBpe0y3JN7bdeL1AnZxqlSJ+gX2BfRZaoLnQzdTcUW+VUIRBwRsLJCFqGo6GAATe2kDbDDZshSKkP8sJnbmbty7BY9j5PTe1tXqDwCT0l7WZtq+K6WRxFVay44xU=
