language: node_js
node_js: 4
before_install:
  - 'git config --global user.email "algobot@users.noreply.github.com"'
  - 'git config --global user.name "algobot"'
  - npm prune
  - rvm install 2.2.0
  - rvm use 2.2.0
before_cache: npm prune
install: npm install
script: ./scripts/test-ci.sh
after_script: ./scripts/travis-after-script.sh
branches:
  only:
    - master
    - develop
sudo: false
cache:
  directories:
    - node_modules
env:
  global:
    # TODO: add necessary keys for cache, deploy
